### PR TITLE
DLPX-75340 bootcount not incremented after reboot

### PR DESCRIPTION
**Pull request by pcd1193182**
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5341/ (failure appears to be unrelated)

Ultimately, there are a number of issues being fixed in this PR. The first is to handle endianness variations in the envblock by checking the ZEC_MAGIC. The second is to modify the open process of the nvlist-based envblock to store the other vbe data in addition to the contents of the envblk file. The third is to modify reading and writing processes to do their operations entirely based on the stored structure.

This patch has also been tested manually by rebooting the system until it fails into the recovery environment, and waiting five minutes after a reboot to verify the bootcount resets.

### CODE REVIEW

**Review by pzakha — APPROVED** [review]
The logic seems fine to me, but I've got a few questions:

> The first is to handle endianness variations in the envblock by checking the ZEC_MAGIC"

It seems like we are always assuming that the version is written on-disk in big endian. Is this the desired behaviour? I'm asking because that comment seems to imply that it can be different.

Regarding testing:
1. Have you tried writing various nvlists to see how they are stored on-disk?
2. Have you tested the error handling case where the provided nvlist is too long & the boundary case where it's either just long enough to fit or 1 byte too long? I think it might be useful here.

**Comment by pcd1193182** [comment]
You're right, I forgot to include part of the endianness handling. What's here works for our use case, but not the general one. I'll fix that.

I didn't test with very long nvlists, but I'll do some manual testing of that. We of course don't care, since our nvlists are only ever a single entry with a single uint64, but you're right that it would be good to test more extreme cases.

**Review by prakashsurya — APPROVED** [review]
I'm not familiar with this code, but looks reasonable to me.

**Comment by pcd1193182** [comment]
The endianness code was right, it turns out. The kernel writes vbe_version using ntohll, so the data is always stored as big-endian.

**Comment by pzakha** [comment]
> The endianness code was right, it turns out. The kernel writes vbe_version using ntohll, so the data is always stored as big-endian.

Okay, that makes sense. I think a short comment would be useful for this type of things.

**Pull request merged**
